# Generated by Django 4.1.6 on 2023-02-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
