# Generated by Django 4.1.6 on 2023-02-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_blogposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
